### ISSUE TITLE
Unable to find Starting Point

### ISSUE THREAD

**Issue by sidrashahbaz** [LinkedDataFragments/Client.Java#13]
Hi, 
I have downloaded the source code and trying to use it with my webservices, I have some queries:
1. What is going to be the input of this client? query or fragment (subject, predicate, object)? 
2. What's the the starting point? Which function I need to call for initiating process?

**Note:** Checked Testcases to figure out above queries, but did not helped me.

Thanks

**Comment by mielvds** [comment]
Hi, 

Did you check the Readme? 

Here's some starting code wit jena:

```
LinkedDataFragmentGraph ldfg = new    LinkedDataFragmentGraph("http://data.linkeddatafragments.org/dbpedia");
Model model =       ModelFactory.createModelForGraph(ldfg);
```

The starting point is any fragment URL, like in this case `http://data.linkeddatafragments.org/dbpedia`,  but can be a more specific fragment too.
