### ISSUE TITLE
provide support for latest Jena version

### ISSUE THREAD

**Issue by m1ci** [LinkedDataFragments/Client.Java#5]
Currently, the client is dependent on `apache-jena-libs` version `2.10.1` which unfortunately does not support JSON-LD. Is it possible that you update to the client to some higher Jena version higher than 2.12.0?

The current dependency:

```
      <dependency>
          <groupId>org.apache.jena</groupId>
          <artifactId>apache-jena-libs</artifactId>
          <type>pom</type>
          <version>2.10.1</version>
      </dependency>
```

**Comment by RubenVerborgh** [comment]
Sure! Would you mind doing a pull request?

**Comment by m1ci** [comment]
cool, actually some fixes should be done in the code, e.g. `ReorderTransformationBase` does not exist anymore in higher Jena versions ...

Will try to fix them, and let you know.

**Comment by m1ci** [comment]
made some changes to support Jena 2.13.0 and it works to me. The pull request here: https://github.com/LinkedDataFragments/Client.Java/pull/6

**Comment by RubenVerborgh** [comment]
Thanks!
